version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    environment:
      PORT: ${PORT}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      BOT_VERIFICATION_TOKEN: ${BOT_VERIFICATION_TOKEN}
      MARIADB_HOSTNAME: back-end_mariadb_1
    volumes:
      - ./:/go/src/github.com/hackathon-21-spring-02/back-end
    # entrypoint: dockerize -timeout 60s -wait tcp://mysql:3306
    command: ./main
    expose:
      - "80"
      - "6060"
    ports:
      - "3000:3000"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: 21hack02
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./mysql/data:/var/lib/mysql:z
      - ./mysql/init:/docker-entrypoint-initdb.d:z
